Repository 100mslive/100ms-react-native, pull requests merged in 2023-04, with the labels that each got.

#962 Release 1.3.0: Release to main branch
  android/src/main/java/com/reactnativehmssdk/HMSDecoder.kt
  android/src/main/java/com/reactnativehmssdk/HMSManager.kt
  android/src/main/java/com/reactnativehmssdk/HMSRNSDK.kt
  example/ExampleAppChangelog.txt
  example/android/Gemfile.lock
  example/android/app/build.gradle
  example/ios/Gemfile.lock
  example/ios/Podfile.lock
  example/ios/RNHMSExample.xcodeproj/project.pbxproj
  example/ios/RNHMSExample/Info.plist
  example/package-lock.json
  example/package.json
  example/src/components/ChatWindow.tsx
  example/src/components/DefaultModal.tsx
  example/src/components/PreviewModal.tsx
  example/src/components/RoomSettingsModalContent.tsx
  example/src/navigator/index.tsx
  example/src/screens/MeetingScreen/DisplayTrack.tsx
  example/src/screens/MeetingScreen/GridView.tsx
  example/src/screens/MeetingScreen/HLSView.tsx
  example/src/screens/MeetingScreen/Modals.tsx
  example/src/screens/MeetingScreen/PeerDisplayView.tsx
  example/src/screens/MeetingScreen/Tile.tsx
  example/src/screens/MeetingScreen/TilesContainer.tsx
  example/src/screens/MeetingScreen/index.tsx
  example/src/screens/QRCode/index.tsx
  example/src/screens/Welcome/index.tsx
  example/src/utils/functions.ts
  ios/HMSDecoder.swift
  ios/HMSManager.m
  ios/HMSManager.swift
  ios/HMSRNSDK.swift
  ios/HMSView.swift
  package-lock.json
  package.json
  sdk-versions.json
  src/classes/HMSAudioNode.ts
  src/classes/HMSConstants.ts
  src/classes/HMSEncoder.ts
  src/classes/HMSLocalPeer.ts
  src/classes/HMSLogger.ts
  src/classes/HMSNativeEventEmitter.ts
  src/classes/HMSPeer.ts
  src/classes/HMSPeerUpdate.ts
  src/classes/HMSPeersCache.ts
  src/classes/HMSRemotePeer.ts
  src/classes/HMSRoom.ts
  src/classes/HMSRoomCache.ts
  src/classes/HMSSDK.tsx
  src/classes/HMSUpdateListenerActions.ts
  src/classes/HmsView.tsx
Labels: chore

#964 feat: added room code apis
  android/src/main/java/com/reactnativehmssdk/HMSManager.kt
  android/src/main/java/com/reactnativehmssdk/HMSRNSDK.kt
  example/ExampleAppChangelog.txt
  example/android/Gemfile.lock
  example/android/app/build.gradle
  example/ios/Gemfile.lock
  example/ios/Podfile.lock
  example/ios/RNHMSExample.xcodeproj/project.pbxproj
  example/ios/RNHMSExample/Info.plist
  example/package-lock.json
  example/package.json
  example/src/screens/Welcome/index.tsx
  example/src/services/index.ts
  example/src/utils/functions.ts
  ios/HMSManager.m
  ios/HMSManager.swift
  ios/HMSRNSDK.swift
  package-lock.json
  package.json
  sdk-versions.json
  src/classes/HMSSDK.tsx
Labels: enhancement

#998 Added Advanced Camera Controls APIs
  android/src/main/java/com/reactnativehmssdk/HMSManager.kt
  android/src/main/java/com/reactnativehmssdk/HMSRNSDK.kt
  android/src/main/java/com/reactnativehmssdk/HMSView.kt
  example/ExampleAppChangelog.txt
  example/android/Gemfile.lock
  example/android/app/build.gradle
  example/android/app/src/main/AndroidManifest.xml
  example/ios/Gemfile.lock
  example/ios/Podfile.lock
  example/ios/RNHMSExample.xcodeproj/project.pbxproj
  example/ios/RNHMSExample/Info.plist
  example/package-lock.json
  example/package.json
  example/src/components/ChatWindow.tsx
  example/src/components/PeerRTCStatsContainer.tsx
  example/src/components/PeerRTCStatsView.tsx
  example/src/components/PeerSettingsModalContent.tsx
  example/src/components/StreamingQualityModalContent.tsx
  example/src/screens/MeetingScreen/DisplayTrack.tsx
  example/src/screens/MeetingScreen/GridView.tsx
  example/src/screens/MeetingScreen/Modals.tsx
  example/src/screens/MeetingScreen/index.tsx
  example/src/utils/functions.ts
  ios/HMSDecoder.swift
  ios/HMSManager.m
  ios/HMSManager.swift
  ios/HMSRNSDK.swift
  package-lock.json
  src/classes/HMSCameraControl.ts
  src/classes/HMSEncoder.ts
  src/classes/HMSQualityLimitationReason.ts
  src/classes/HMSQualityLimitationReasons.ts
  src/classes/HMSRoomUpdate.ts
  src/classes/HMSSDK.tsx
  src/index.ts
Labels: enhancement, P0
