Repository 100mslive/100ms-react-native, pull requests merged in 2023-05, with the labels that each got.

#1007 Feature/1001 - Add support for music mode
  example/src/components/JoinSettingsModalContent.tsx
  example/src/redux/actionTypes.ts
  example/src/redux/actions/index.ts
  example/src/redux/reducers/appState.ts
  example/src/screens/Welcome/index.tsx
  ios/HMSHelper.swift
  src/classes/HMSAudioTrackSettings.ts
  src/classes/HMSEncoder.ts
  src/classes/HMSIOSAudioMode.ts
  src/index.ts
Labels: enhancement, P0

#1011 Feature/989 - Added Session Store
  .trunk/.gitignore
  .trunk/config/.yamllint.yaml
  .trunk/trunk.yaml
  android/src/main/java/com/reactnativehmssdk/HMSManager.kt
  android/src/main/java/com/reactnativehmssdk/HMSRNSDK.kt
  android/src/main/java/com/reactnativehmssdk/HMSView.kt
  example/ExampleAppChangelog.txt
  example/android/app/build.gradle
  example/ios/Podfile.lock
  example/ios/RNHMSExample.xcodeproj/project.pbxproj
  example/ios/RNHMSExample/Info.plist
  example/package-lock.json
  example/src/components/ChatWindow.tsx
  example/src/components/PeerSettingsModalContent.tsx
  example/src/redux/reducers/userState.ts
  example/src/screens/MeetingScreen/GridView.tsx
  example/src/screens/MeetingScreen/index.tsx
  example/src/screens/Welcome/index.tsx
  example/src/utils/functions.ts
  ios/HMSConstants.swift
  ios/HMSDecoder.swift
  ios/HMSManager.m
  ios/HMSManager.swift
  ios/HMSRNSDK.swift
  src/classes/HMSIOSAudioMode.ts
  src/classes/HMSSDK.tsx
  src/classes/HMSSessionStore.ts
Labels: enhancement, P0

#1027 Session store bug fixes
  .trunk/trunk.yaml
  android/src/main/java/com/reactnativehmssdk/HMSRNSDK.kt
  example/android/app/build.gradle
  example/ios/RNHMSExample.xcodeproj/project.pbxproj
  example/ios/RNHMSExample/Info.plist
  example/src/components/ChatWindow.tsx
  example/src/components/PeerSettingsModalContent.tsx
  example/src/redux/actions/index.ts
  example/src/redux/reducers/message.ts
  example/src/screens/MeetingScreen/PIPView.tsx
  example/src/screens/MeetingScreen/index.tsx
  example/src/utils/functions.ts
  ios/HMSConstants.swift
  ios/HMSManager.swift
  ios/HMSRNSDK.swift
  src/classes/HMSSessionStore.ts
  src/classes/HMSUpdateListenerActions.ts
  src/index.ts
  src/utils/emitter/EventEmitter.ts
  src/utils/emitter/_EmitterSubscription.ts
  src/utils/emitter/_EventSubscription.ts
  src/utils/emitter/_EventSubscriptionVendor.ts
  src/utils/index.ts
Labels: enhancement, P0

#1033 Fixed lint warnings
  android/src/main/java/com/reactnativehmssdk/HMSAudioshareActivity.kt
  android/src/main/java/com/reactnativehmssdk/HMSDecoder.kt
  android/src/main/java/com/reactnativehmssdk/HMSHelper.kt
  android/src/main/java/com/reactnativehmssdk/HMSSDKViewManager.kt
  android/src/main/java/com/reactnativehmssdk/HmsScreenshareActivity.kt
  android/src/main/java/com/reactnativehmssdk/PipActionReceiver.kt
  example/ios/Podfile.lock
Labels: chore

#1034 Updated applying HMSView scaletype
  android/src/main/java/com/reactnativehmssdk/HMSSDKViewManager.kt
  android/src/main/java/com/reactnativehmssdk/HMSView.kt
  example/ExampleAppChangelog.txt
  example/android/Gemfile.lock
  example/android/app/build.gradle
  example/ios/Gemfile.lock
  example/ios/Podfile.lock
  example/ios/RNHMSExample.xcodeproj/project.pbxproj
  example/ios/RNHMSExample/Info.plist
  example/package-lock.json
  example/src/components/PreviewModal.tsx
  example/src/screens/MeetingScreen/PeerDisplayView.tsx
  example/src/screens/Welcome/index.tsx
  src/classes/HmsView.tsx
Labels: bug, P0

#1039 Release 1.6.1: Develop to main
  .trunk/trunk.yaml
  android/src/main/java/com/reactnativehmssdk/HMSAudioshareActivity.kt
  android/src/main/java/com/reactnativehmssdk/HMSDecoder.kt
  android/src/main/java/com/reactnativehmssdk/HMSHelper.kt
  android/src/main/java/com/reactnativehmssdk/HMSSDKViewManager.kt
  android/src/main/java/com/reactnativehmssdk/HMSView.kt
  android/src/main/java/com/reactnativehmssdk/HmsScreenshareActivity.kt
  android/src/main/java/com/reactnativehmssdk/PipActionReceiver.kt
  example/ExampleAppChangelog.txt
  example/android/Gemfile.lock
  example/android/app/build.gradle
  example/ios/Gemfile.lock
  example/ios/Podfile.lock
  example/ios/RNHMSExample.xcodeproj/project.pbxproj
  example/ios/RNHMSExample/Info.plist
  example/package-lock.json
  example/package.json
  example/src/components/PreviewModal.tsx
  example/src/screens/MeetingScreen/PeerDisplayView.tsx
  example/src/screens/Welcome/index.tsx
  package-lock.json
  package.json
  sdk-versions.json
  src/classes/HmsView.tsx
Labels: chore

#1042 corrected lint warnings
  example/src/components/LiveButton.tsx
  example/src/components/PeerSettingsModalContent.tsx
  example/src/components/StreamingQualityModalContent.tsx
  example/src/screens/MeetingScreen/Modals.tsx
  example/src/screens/MeetingScreen/index.tsx
  sample-apps/rn-quickstart-app/src/screens/MeetingScreen/hooks.ts
Labels: chore

#1044 Add messageId to HMSMessage
  android/build.gradle
  android/src/main/java/com/reactnativehmssdk/HMSRNSDK.kt
  example/ExampleAppChangelog.txt
  example/android/Gemfile.lock
  example/ios/Gemfile.lock
  example/package-lock.json
  example/package.json
  example/src/components/ChatWindow.tsx
  example/src/screens/MeetingScreen/index.tsx
  ios/HMSRNSDK.swift
  package-lock.json
  sdk-versions.json
  src/classes/HMSEncoder.ts
  src/classes/HMSMessage.ts
  src/classes/HMSSDK.tsx
Labels: enhancement

#1043 Release 1.6.2: To main
  android/build.gradle
  android/src/main/java/com/reactnativehmssdk/HMSRNSDK.kt
  example/ExampleAppChangelog.txt
  example/android/Gemfile.lock
  example/android/app/build.gradle
  example/ios/Gemfile.lock
  example/ios/Podfile.lock
  example/ios/RNHMSExample.xcodeproj/project.pbxproj
  example/ios/RNHMSExample/Info.plist
  example/package-lock.json
  example/package.json
  example/src/components/ChatWindow.tsx
  example/src/components/LiveButton.tsx
  example/src/components/PeerSettingsModalContent.tsx
  example/src/components/StreamingQualityModalContent.tsx
  example/src/screens/MeetingScreen/Modals.tsx
  example/src/screens/MeetingScreen/index.tsx
  ios/HMSRNSDK.swift
  package-lock.json
  package.json
  sample-apps/rn-quickstart-app/package-lock.json
  sample-apps/rn-quickstart-app/package.json
  sample-apps/rn-quickstart-app/src/screens/MeetingScreen/hooks.ts
  sample-apps/rn-quickstart-app/yarn.lock
  sdk-versions.json
  src/classes/HMSEncoder.ts
  src/classes/HMSMessage.ts
  src/classes/HMSSDK.tsx
Labels: chore
