Repository 100mslive/100ms-react-native, pull requests merged in 2023-06, with the labels that each got.

#1057 Bug/1056 ios app crashing on rejoin
  .trunk/trunk.yaml
  example/ExampleAppChangelog.txt
  example/android/Gemfile.lock
  example/ios/Gemfile.lock
  example/ios/Podfile.lock
  example/package-lock.json
  example/src/screens/MeetingScreen/index.tsx
  ios/HMSRNSDK.swift
  package-lock.json
Labels: bug, P0

#1070 Fix: When HMSPeer leaves the Room, its properties becomes undefined
  android/src/main/java/com/reactnativehmssdk/HMSRNSDK.kt
  example/src/screens/MeetingScreen/Modals.tsx
  example/src/screens/MeetingScreen/index.tsx
  ios/HMSRNSDK.swift
  src/classes/HMSPeer.ts
  src/classes/HMSPeersCache.ts
Labels: bug, P0

#1073 Removed reanimated package
  .trunk/trunk.yaml
  example/android/Gemfile.lock
  example/android/app/proguard-rules.pro
  example/babel.config.js
  example/ios/Gemfile.lock
  example/ios/Podfile.lock
  example/package-lock.json
  example/package.json
  example/src/components/Emoticon.tsx
  example/src/components/HLSPlayerEmoticons.tsx
  example/src/screens/MeetingScreen/index.tsx
  package-lock.json
Labels: bug, P0

#1065 Added HMS HLS player
  .trunk/trunk.yaml
  android/build.gradle
  android/src/main/java/com/reactnativehmssdk/HMSHLSPlayer.kt
  android/src/main/java/com/reactnativehmssdk/HMSHLSPlayerManager.kt
  android/src/main/java/com/reactnativehmssdk/HmssdkPackage.kt
  android/src/main/res/layout/player_view.xml
  example/ExampleAppChangelog.txt
  example/android/Gemfile.lock
  example/android/app/build.gradle
  example/android/build.gradle
  example/android/gradle.properties
  example/ios/Gemfile.lock
  example/ios/Podfile.lock
  example/ios/RNHMSExample.xcodeproj/project.pbxproj
  example/ios/RNHMSExample/Info.plist
  example/package-lock.json
  example/package.json
  example/src/components/CustomHLSPlayerControls.tsx
  example/src/components/HLSPlayerEmoticons.tsx
  example/src/components/HLSPlayerStatsView.tsx
  example/src/components/JoinSettingsModalContent.tsx
  example/src/components/RoomSettingsModalContent.tsx
  example/src/redux/actionTypes.ts
  example/src/redux/actions/index.ts
  example/src/redux/reducers/appState.ts
  example/src/screens/MeetingScreen/HLSView.tsx
  example/src/screens/MeetingScreen/Modals.tsx
  example/src/screens/MeetingScreen/index.tsx
  example/src/screens/MeetingScreen/styles.ts
  example/src/utils/hooks.ts
  example/src/utils/types.ts
  ios/HMSDecoder.swift
  ios/HMSHLSPlayerManager.m
  ios/HMSHLSPlayerManager.swift
  package-lock.json
  package.json
  react-native-hms.podspec
  sdk-versions.json
  src/classes/HMSEncoder.ts
  src/classes/HMSPeerUpdate.ts
  src/classes/HMSSDK.tsx
  src/components/HMSHLSPlayer/HMSHLSPlayer.tsx
  src/components/HMSHLSPlayer/RCTHMSHLSPlayer.ts
  src/components/HMSHLSPlayer/hooks.ts
  src/components/HMSHLSPlayer/index.ts
  src/index.ts
  src/stores/hls-player-playback-slice.ts
  src/stores/hls-player-stats-store.ts
  src/stores/hms-store.ts
  src/stores/types.ts
  src/types.ts
Labels: enhancement, P0

#1069 Feature/1068: Enabled S/W Echo cancellation
  android/build.gradle
  android/src/main/java/com/reactnativehmssdk/HMSHelper.kt
  example/ExampleAppChangelog.txt
  example/android/Gemfile.lock
  example/android/app/build.gradle
  example/android/build.gradle
  example/ios/Gemfile.lock
  example/ios/Podfile.lock
  example/ios/RNHMSExample.xcodeproj/project.pbxproj
  example/ios/RNHMSExample/Info.plist
  example/package-lock.json
  example/src/components/PreviewModal.tsx
  example/src/screens/MeetingScreen/PeerDisplayView.tsx
  package-lock.json
  release-apps.sh
  sample-apps/rn-quickstart-app/src/screens/MeetingScreen/components/PeerDisplayView.tsx
Labels: enhancement, P0

#1078 Update README.md
  README.md
Labels: documentation
