Repository 100mslive/100ms-react-native, pull requests merged in 2023-09, with the labels that each got.

#1177 Send peer name always in peer data to apps
  packages/react-native-hms/android/src/main/java/com/reactnativehmssdk/HMSDecoder.kt
  packages/react-native-hms/ios/HMSDecoder.swift
  packages/react-native-hms/src/classes/HMSEncoder.ts
  packages/react-native-hms/src/classes/HMSLocalPeer.ts
  packages/react-native-hms/src/classes/HMSPeer.ts
  packages/react-native-hms/src/classes/HMSRemotePeer.ts
Labels: bug, P0

#1181 handling no publish params for local peer
  .trunk/trunk.yaml
  packages/react-native-hms/example/package-lock.json
  packages/react-native-hms/example/src/screens/MeetingScreen/index.tsx
  packages/react-native-hms/package-lock.json
  packages/react-native-room-kit/example/ExampleAppChangelog.txt
  packages/react-native-room-kit/example/package-lock.json
  packages/react-native-room-kit/package-lock.json
  packages/react-native-room-kit/src/HMSRoomSetup.tsx
  packages/react-native-room-kit/src/assets/welcome.png
  packages/react-native-room-kit/src/components/MiniView.tsx
  packages/react-native-room-kit/src/components/WelcomeInMeeting.tsx
  packages/react-native-room-kit/src/hooks-util.ts
Labels: enhancement, P0

#1189 Fix: remove unsupported options on tiles
  packages/react-native-room-kit/src/components/PeerSettingsModalContent.tsx
  packages/react-native-room-kit/src/components/PeerVideoTile/PeerVideoTileView.tsx
Labels: bug, P0

#1187 Fix: options on screenshare tiles
  packages/react-native-room-kit/src/components/PeerVideoTile/PeerVideoTileView.tsx
Labels: bug, P0

#1188 Fix/prebuilt sev2 bugfixes
  packages/react-native-room-kit/README.md
  packages/react-native-room-kit/example/android/app/build.gradle
  packages/react-native-room-kit/example/ios/Podfile.lock
  packages/react-native-room-kit/example/ios/RNExample.xcodeproj/project.pbxproj
  packages/react-native-room-kit/example/ios/RNExample/Info.plist
  packages/react-native-room-kit/example/package-lock.json
  packages/react-native-room-kit/example/package.json
  packages/react-native-room-kit/package-lock.json
  packages/react-native-room-kit/package.json
  packages/react-native-room-kit/src/HMSPrebuilt.tsx
  packages/react-native-room-kit/src/components/Chat/ChatBanner.tsx
  packages/react-native-room-kit/src/components/Chat/ChatList.tsx
  packages/react-native-room-kit/src/components/HMSChat.tsx
  packages/react-native-room-kit/src/components/HMSHLSMessage.tsx
  packages/react-native-room-kit/src/components/HMSKeyboardAvoidingView.tsx
  packages/react-native-room-kit/src/components/PeerSettingsModalContent.tsx
  packages/react-native-room-kit/src/components/PeerVideoTile/PeerVideoTileView.tsx
Labels: bug, P0

#1191 Fix: Changing Avatar Size If Inset Mode
  packages/react-native-room-kit/src/components/PeerVideoTile/AvatarView.tsx
  packages/react-native-room-kit/src/components/PeerVideoTile/PeerVideoTileView.tsx
Labels: bug, P0

#1192 Android foreground service
  packages/react-native-room-kit/example/android/app/src/main/AndroidManifest.xml
  packages/react-native-room-kit/example/package-lock.json
  packages/react-native-room-kit/example/package.json
  packages/react-native-room-kit/example/src/screens/HMSPrebuiltScreen/index.tsx
Labels: bug, P0

#1193 fix: removed Right Aligning of Chat Messages
  packages/react-native-room-kit/src/components/Chat/ChatMessage.tsx
  packages/react-native-room-kit/src/components/HMSHLSMessage.tsx
Labels: bug, P0

#1194 send onError only when it is received from Native SDK
  packages/react-native-hms/android/src/main/java/com/reactnativehmssdk/HMSRNSDK.kt
  packages/react-native-hms/ios/HMSRNSDK.swift
Labels: bug, P0

#1196 fix: invoke handleLeave callback set by app when exiting from Preview
  packages/react-native-hms/android/build.gradle
  packages/react-native-room-kit/example/android/app/build.gradle
  packages/react-native-room-kit/example/ios/RNExample.xcodeproj/project.pbxproj
  packages/react-native-room-kit/example/ios/RNExample/Info.plist
  packages/react-native-room-kit/src/HMSRoomSetup.tsx
  packages/react-native-room-kit/src/components/Chat/ChatFilterView.tsx
  packages/react-native-room-kit/src/components/ChatAndParticipants/ChatAndParticipantsBottomSheet.tsx
  packages/react-native-room-kit/src/components/ChatAndParticipants/ChatAndParticipantsView.tsx
  packages/react-native-room-kit/src/components/DisplayView.tsx
  packages/react-native-room-kit/src/components/HMSManageLeave.tsx
  packages/react-native-room-kit/src/components/Header.tsx
  packages/react-native-room-kit/src/components/Participants/ParticipantsGroupHeader.tsx
  packages/react-native-room-kit/src/components/Participants/ParticipantsGroupOptions.tsx
  packages/react-native-room-kit/src/components/Participants/ParticipantsHeader.tsx
  packages/react-native-room-kit/src/components/Participants/ParticipantsItem.tsx
  packages/react-native-room-kit/src/components/Participants/ParticipantsItemOption.tsx
  packages/react-native-room-kit/src/components/Participants/ParticipantsItemOptions.tsx
  packages/react-native-room-kit/src/components/Participants/ParticipantsList.tsx
  packages/react-native-room-kit/src/components/Participants/ParticipantsSeachInput.tsx
  packages/react-native-room-kit/src/components/Participants/SearchableParticipantsView.tsx
  packages/react-native-room-kit/src/components/ParticipantsBottomSheet.tsx
  packages/react-native-room-kit/src/components/ParticipantsModal.tsx
  packages/react-native-room-kit/src/hooks-util.ts
  packages/react-native-room-kit/src/redux/actionTypes.ts
  packages/react-native-room-kit/src/redux/actions/index.ts
  packages/react-native-room-kit/src/redux/reducers/hmsStates.ts
Labels: bug, P0

#1197 Fix: dont show more options to viewer roles
  .trunk/trunk.yaml
  packages/react-native-room-kit/example/android/app/build.gradle
  packages/react-native-room-kit/example/ios/RNExample.xcodeproj/project.pbxproj
  packages/react-native-room-kit/example/ios/RNExample/Info.plist
  packages/react-native-room-kit/src/components/PeerVideoTile/PeerVideoTileView.tsx
Labels: bug, P0

#1201 setting edge to edge player based upon stream size
  packages/react-native-hms/ios/HMSHLSPlayerManager.swift
Labels: bug, P0

#1203 Feature: added lottie animations for active speaker
  packages/react-native-room-kit/example/ios/Podfile.lock
  packages/react-native-room-kit/example/package-lock.json
  packages/react-native-room-kit/example/package.json
  packages/react-native-room-kit/package-lock.json
  packages/react-native-room-kit/package.json
  packages/react-native-room-kit/src/assets/audio-level-white.json
  packages/react-native-room-kit/src/components/PeerVideoTile/PeerAudioIndicator.tsx
  packages/react-native-room-kit/src/components/PeerVideoTile/PeerAudioMutedIndicator.tsx
  packages/react-native-room-kit/src/components/PeerVideoTile/PeerVideoTileView.tsx
  packages/react-native-room-kit/src/hooks-util.ts
  packages/react-native-room-kit/src/redux/actionTypes.ts
  packages/react-native-room-kit/src/redux/actions/index.ts
  packages/react-native-room-kit/src/redux/reducers/hmsStates.ts
Labels: enhancement, P0

#1205 Honoring layout config states
  packages/react-native-hms/example/ios/Podfile.lock
  packages/react-native-hms/example/package-lock.json
  packages/react-native-hms/package-lock.json
  packages/react-native-hms/sdk-versions.json
  packages/react-native-room-kit/example/android/app/build.gradle
  packages/react-native-room-kit/example/ios/Podfile.lock
  packages/react-native-room-kit/example/ios/RNExample.xcodeproj/project.pbxproj
  packages/react-native-room-kit/example/ios/RNExample/Info.plist
  packages/react-native-room-kit/example/package-lock.json
  packages/react-native-room-kit/package-lock.json
  packages/react-native-room-kit/src/components/EndRoomModalContent.tsx
  packages/react-native-room-kit/src/components/Footer.tsx
  packages/react-native-room-kit/src/components/HMSManageLeave.tsx
  packages/react-native-room-kit/src/components/RoomSettingsModalContent.tsx
  packages/react-native-room-kit/src/hooks-util.ts
Labels: enhancement, P0

#1207 setting video player aspect ratio as per video stream content size
  packages/react-native-hms/android/src/main/java/com/reactnativehmssdk/HMSHLSPlayer.kt
  packages/react-native-hms/android/src/main/res/layout/player_view.xml
  packages/react-native-hms/src/components/HMSHLSPlayer/HMSHLSPlayer.tsx
  packages/react-native-hms/src/types.ts
  packages/react-native-room-kit/src/components/HLSView.tsx
Labels: bug, P0

#1208 Prebuilt: Honouring video Inset tile layout configuration
  packages/react-native-room-kit/src/HMSRoomSetup.tsx
  packages/react-native-room-kit/src/components/PeerSettingsModalContent.tsx
  packages/react-native-room-kit/src/hooks-util-selectors.tsx
  packages/react-native-room-kit/src/hooks-util.ts
Labels: enhancement, P0

#1209 added blurview ui for reconnection state
  packages/react-native-hms/android/src/main/java/com/reactnativehmssdk/HMSRNSDK.kt
  packages/react-native-hms/ios/HMSRNSDK.swift
  packages/react-native-room-kit/src/components/Meeting.tsx
  packages/react-native-room-kit/src/components/MeetingScreenContent.tsx
  packages/react-native-room-kit/src/components/ReconnectionView.tsx
  packages/react-native-room-kit/src/hooks-util.ts
  packages/react-native-room-kit/src/redux/actionTypes.ts
  packages/react-native-room-kit/src/redux/actions/index.ts
  packages/react-native-room-kit/src/redux/reducers/hmsStates.ts
Labels: enhancement, P0

#1210 Fix/hiding participants list tab from chat sheet
  packages/react-native-room-kit/src/components/ChatAndParticipants/ChatAndParticipantsHeader.tsx
Labels: bug, P0

#1211 Fix chat and participants bugs
  packages/react-native-room-kit/src/HMSRoomSetup.tsx
  packages/react-native-room-kit/src/components/ChatAndParticipants/ChatAndParticipantsHeader.tsx
  packages/react-native-room-kit/src/components/ChatAndParticipants/ChatAndParticipantsView.tsx
  packages/react-native-room-kit/src/components/DisplayView.tsx
  packages/react-native-room-kit/src/components/Footer.tsx
  packages/react-native-room-kit/src/components/HMSLiveIndicator.tsx
  packages/react-native-room-kit/src/components/RoomSettingsModalContent.tsx
  packages/react-native-room-kit/src/hooks-util-selectors.tsx
  packages/react-native-room-kit/src/hooks-util.ts
Labels: bug, P0

#1212 hand-raise button will appear in room settings modal for non-viewers
  packages/react-native-room-kit/src/components/Footer.tsx
  packages/react-native-room-kit/src/components/RoomSettingsModalContent.tsx
Labels: bug, P0

#1213 Refactored chat and participants code
  packages/react-native-room-kit/src/components/ChatAndParticipants/ChatAndParticipantsBottomSheet.tsx
  packages/react-native-room-kit/src/components/ChatAndParticipants/ChatAndParticipantsHeader.tsx
  packages/react-native-room-kit/src/components/ChatAndParticipants/ChatAndParticipantsView.tsx
  packages/react-native-room-kit/src/components/ChatAndParticipants/ChatView.tsx
  packages/react-native-room-kit/src/components/ChatAndParticipants/ParticipantsView.tsx
  packages/react-native-room-kit/src/components/DisplayView.tsx
  packages/react-native-room-kit/src/components/Footer.tsx
  packages/react-native-room-kit/src/components/HLSFooter.tsx
  packages/react-native-room-kit/src/components/HMSChat.tsx
  packages/react-native-room-kit/src/components/HMSLiveIndicator.tsx
  packages/react-native-room-kit/src/components/OverlayedViews.tsx
  packages/react-native-room-kit/src/components/Participants/ParticipantsHeader.tsx
  packages/react-native-room-kit/src/components/Participants/index.ts
  packages/react-native-room-kit/src/components/ParticipantsBottomSheet.tsx
  packages/react-native-room-kit/src/components/ParticipantsModal.tsx
  packages/react-native-room-kit/src/components/RoomSettingsModalContent.tsx
  packages/react-native-room-kit/src/hooks-util.ts
  packages/react-native-room-kit/src/utils/types.ts
Labels: enhancement

#1214 Fixed local tile creation logic
  packages/react-native-room-kit/src/HMSRoomSetup.tsx
  packages/react-native-room-kit/src/hooks-util.ts
Labels: P0

#1215 Prebuilt: Fixed wrong role change on remove from stage
  packages/react-native-room-kit/src/components/Participants/ParticipantsItemOptions.tsx
  packages/react-native-room-kit/src/components/PreviewForRoleChangeModal.tsx
  packages/react-native-room-kit/src/utils/functions.ts
Labels: bug, P0

#1226 added handraise first class APIs
  .trunk/trunk.yaml
  packages/react-native-hms/android/build.gradle
  packages/react-native-hms/android/src/main/java/com/reactnativehmssdk/HMSDecoder.kt
  packages/react-native-hms/android/src/main/java/com/reactnativehmssdk/HMSManager.kt
  packages/react-native-hms/android/src/main/java/com/reactnativehmssdk/HMSRNSDK.kt
  packages/react-native-hms/example/android/Gemfile.lock
  packages/react-native-hms/example/ios/Gemfile.lock
  packages/react-native-hms/example/ios/Podfile.lock
  packages/react-native-hms/example/package-lock.json
  packages/react-native-hms/example/package.json
  packages/react-native-hms/ios/HMSDecoder.swift
  packages/react-native-hms/ios/HMSManager.m
  packages/react-native-hms/ios/HMSManager.swift
  packages/react-native-hms/ios/HMSRNSDK.swift
  packages/react-native-hms/package-lock.json
  packages/react-native-hms/package.json
  packages/react-native-hms/sdk-versions.json
  packages/react-native-hms/src/classes/HMSPeer.ts
  packages/react-native-hms/src/classes/HMSPeerUpdate.ts
  packages/react-native-hms/src/classes/HMSPeersCache.ts
  packages/react-native-hms/src/classes/HMSSDK.tsx
  packages/react-native-room-kit/example/ExampleAppChangelog.txt
  packages/react-native-room-kit/example/android/Gemfile.lock
  packages/react-native-room-kit/example/android/app/build.gradle
  packages/react-native-room-kit/example/ios/Podfile.lock
  packages/react-native-room-kit/example/ios/RNExample.xcodeproj/project.pbxproj
  packages/react-native-room-kit/example/ios/RNExample/Info.plist
  packages/react-native-room-kit/example/package-lock.json
  packages/react-native-room-kit/package-lock.json
  packages/react-native-room-kit/src/components/HMSManageRaiseHand.tsx
  packages/react-native-room-kit/src/components/Participants/ParticipantsItem.tsx
  packages/react-native-room-kit/src/components/Participants/ParticipantsItemOptions.tsx
  packages/react-native-room-kit/src/components/PeerVideoTile/PeerMetadata.tsx
  packages/react-native-room-kit/src/components/PeerVideoTile/PeerVideoTileView.tsx
  packages/react-native-room-kit/src/components/PreviewForRoleChangeModal.tsx
  packages/react-native-room-kit/src/components/RoomSettingsModalContent.tsx
  packages/react-native-room-kit/src/hooks-sdk.ts
  packages/react-native-room-kit/src/hooks-util.ts
  packages/react-native-room-kit/src/utils/functions.ts
Labels: enhancement, P0
